name: Tests

on:
  push:
  pull_request:

jobs:
  api-integration-tests:
    name: API integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Run tests
        run: dotnet test MedicalAtention.API.IntegrationTests/MedicalAtention.API.IntegrationTests.csproj --verbosity normal

  app-unit-tests:
    name: App unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Run tests
        run: dotnet test Medical-atentionApp/Medical-atention/Medical-atention.Tests/Medical-atention.Tests.csproj --verbosity normal
